export const moviesFormData = [
  {
    title: "input",
    control: "",
    type: "text",
    label: "title",
    name: "Title",
    value: "",
    required: true,
    regex: "",
    maxLength: "",
    placeholder: "Please enter title",
    error: "Please enter valid  title",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "storyLine",
    name: "storyLine",
    value: "",
    required: true,
    maxLength: "",
    placeholder: "Please enter  storyLine",
    error: "Please enter valid storyLine",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "director",
    name: "director",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter director",
    error: "Please enter valid director",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter type",
    error: "Please enter valid type",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter releseDate",
    error: "Please enter valid releseDate",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter genres",
    error: "Please enter valid genres",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter tags",
    error: "Please enter valid tags",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter cast",
    error: "Please enter valid cast",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter poster",
    error: "Please enter valid poster",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter trailer",
    error: "Please enter valid trailer",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter video",
    error: "Please enter valid video",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter imbRating",
    error: "Please enter valid imbRating",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "type",
    name: "type",
    value: "",
    required: true,
    maxLength: 10,
    placeholder: "Please enter language",
    error: "Please enter valid language",
  },
];
