import {mobileNumberRegEx,gmailRegex} from '../../utility/form-validations'
export const userFormData = [
  {
    title: "input",
    control: "",
    type: "text",
    label: "Name",
    name: "name",
    value: "",
    required: true,
    regex: "",
    maxLength: "",
    placeholder: "Please enter name",
    error: "Please enter valid  name",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "Email",
    name: "email",
    value: "",
    required: true,
    regex: gmailRegex,
    maxLength: "",
    placeholder: "Please enter  email",
    error: "Please enter valid email",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "Phone Number",
    name: "phone_number",
    value: "",
    required: true,
    regex: mobileNumberRegEx,
    maxLength: 10,
    placeholder: "Please enter phone number",
    error: "Please enter valid phone number",
  },
  {
    title: "input",
    control: "",
    type: "text",
    label: "Password",
    name: "password",
    value: "",
    required: true,
    regex: mobileNumberRegEx,
    maxLength: 10,
    placeholder: "Please enter password",
    error: "Please enter valid password",
  },
];
